# Generated by Django 4.2.7 on 2025-08-10 15:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoices.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True, validators=[invoices.validators.validate_invoice_number])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(validators=[invoices.validators.validate_due_date])),
                ('billing_address', models.TextField()),
                ('service_address', models.TextField()),
                ('is_ndis_invoice', models.BooleanField(default=False)),
                ('participant_name', models.CharField(blank=True, max_length=200, validators=[invoices.validators.validate_participant_name])),
                ('ndis_number', models.CharField(blank=True, max_length=20, validators=[invoices.validators.validate_ndis_number])),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[invoices.validators.validate_positive_decimal])),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[invoices.validators.validate_positive_decimal])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[invoices.validators.validate_positive_decimal])),
                ('payment_terms', models.PositiveIntegerField(default=30, validators=[invoices.validators.validate_payment_terms])),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/%Y/%m/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[invoices.validators.validate_quantity])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[invoices.validators.validate_unit_price])),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'invoices_invoice_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoices_in_client__d0ba52_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_in_due_dat_6cc0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_ndis_invoice'], name='invoices_in_is_ndis_738688_idx'),
        ),
    ]
