# Generated by Django 4.2.7 on 2025-09-01 20:32

from decimal import Decimal
from django.db import migrations, models
import invoices.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[invoices.validators.validate_positive_decimal]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[invoices.validators.validate_positive_decimal]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[invoices.validators.validate_positive_decimal]),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deposit_required', 'deposit_paid'], name='invoices_in_deposit_941726_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deposit_paid_date'], name='invoices_in_deposit_106d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('deposit_amount__gte', 0)), name='invoices_invoice_positive_deposit_amount'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('deposit_percentage__gte', 0), ('deposit_percentage__lte', 100)), name='invoices_invoice_valid_deposit_percentage'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('remaining_balance__gte', 0)), name='invoices_invoice_positive_remaining_balance'),
        ),
    ]
