# Generated by Django 4.2.7 on 2025-08-11 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quotes.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotetemplate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Quote Template', 'verbose_name_plural': 'Quote Templates'},
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='access_instructions',
            field=models.TextField(blank=True, help_text='Default access instructions'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of rooms', null=True, validators=[quotes.validators.validate_room_count]),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Default special requirements'),
        ),
        migrations.AddField(
            model_name='quotetemplate',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default property size', max_digits=8, null=True, validators=[quotes.validators.validate_square_meters]),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the template', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='default_service',
            field=models.ForeignKey(blank=True, help_text='Default service for this template', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='name',
            field=models.CharField(help_text='Template name', max_length=200, validators=[quotes.validators.validate_template_name]),
        ),
        migrations.AlterUniqueTogether(
            name='quotetemplate',
            unique_together={('created_by', 'name')},
        ),
        migrations.AddIndex(
            model_name='quotetemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='quotes_quot_created_5f2310_idx'),
        ),
    ]
