# Generated by Django 4.2.7 on 2025-08-11 15:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_alter_quotetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cleaning_type',
            field=models.CharField(choices=[('general', 'General Cleaning'), ('deep', 'Deep Cleaning'), ('end_of_lease', 'End of Lease Cleaning'), ('ndis', 'NDIS Cleaning'), ('commercial', 'Commercial Cleaning'), ('carpet', 'Carpet Cleaning'), ('window', 'Window Cleaning'), ('pressure_washing', 'Pressure Washing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='conversion_rate_applied',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='extras_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_ndis_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='ndis_participant_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number_of_rooms',
            field=models.PositiveIntegerField(validators=[quotes.validators.validate_room_count]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='plan_manager_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='plan_manager_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='postcode',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='quote',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='property_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(max_length=20, unique=True, validators=[quotes.validators.validate_quote_number]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.service'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[quotes.validators.validate_square_meters]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=3),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Job'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='suburb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='support_coordinator_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='support_coordinator_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='travel_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='urgency_level',
            field=models.PositiveIntegerField(choices=[(1, 'Flexible (7+ days)'), (2, 'Standard (3-7 days)'), (3, 'Priority (1-3 days)'), (4, 'Urgent (Same day)'), (5, 'Emergency (ASAP)')], default=2, validators=[quotes.validators.validate_urgency_level]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='urgency_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
