# Generated by Django 4.2.7 on 2025-08-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quotetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
