# Generated by Django 4.2.7 on 2025-08-14 17:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import quotes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_access_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[quotes.validators.validate_square_meters]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='travel_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='urgency_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Item quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default property size', max_digits=10, null=True, validators=[quotes.validators.validate_square_meters]),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('final_price__gte', 0)), name='quotes_quote_positive_final_price'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('number_of_rooms__gt', 0)), name='quotes_quote_positive_room_count'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='quotes_quote_positive_base_price'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('estimated_total__gte', 0)), name='quotes_quote_positive_estimated_total'),
        ),
        migrations.AddConstraint(
            model_name='quoteattachment',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='quotes_quoteattachment_positive_file_size'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quotes_quoteitem_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='quotes_quoteitem_positive_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='quotes_quoteitem_positive_total_price'),
        ),
        migrations.AddConstraint(
            model_name='quoterevision',
            constraint=models.CheckConstraint(check=models.Q(('previous_price__gte', 0)), name='quotes_quoterevision_positive_previous_price'),
        ),
        migrations.AddConstraint(
            model_name='quoterevision',
            constraint=models.CheckConstraint(check=models.Q(('new_price__gte', 0)), name='quotes_quoterevision_positive_new_price'),
        ),
        migrations.AddConstraint(
            model_name='quoterevision',
            constraint=models.CheckConstraint(check=models.Q(('revision_number__gt', 0)), name='quotes_quoterevision_positive_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='quotetemplate',
            constraint=models.CheckConstraint(check=models.Q(('usage_count__gte', 0)), name='quotes_quotetemplate_positive_usage_count'),
        ),
    ]
