# Generated by Django 4.2.7 on 2025-08-18 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_discount_amount_alter_quote_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterevision',
            name='new_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterevision',
            name='new_deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterevision',
            name='previous_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterevision',
            name='previous_deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('deposit_amount__gte', 0)), name='quotes_quote_positive_deposit_amount'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('deposit_percentage__gte', 0), ('deposit_percentage__lte', 100)), name='quotes_quote_valid_deposit_percentage'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('remaining_balance__gte', 0)), name='quotes_quote_positive_remaining_balance'),
        ),
    ]
