# Generated by Django 4.2.7 on 2025-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_add_deposit_tracking_to_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='cleaning_type',
            field=models.CharField(choices=[('general', 'General Cleaning'), ('deep', 'Deep Cleaning'), ('end_of_lease', 'End of Lease Cleaning'), ('ndis', 'NDIS Cleaning'), ('commercial', 'Commercial Cleaning'), ('carpet', 'Carpet Cleaning'), ('window', 'Window Cleaning'), ('pressure_washing', 'Pressure Washing'), ('airbnb', 'Airbnb Turnover'), ('post_renovation', 'Post Renovation'), ('after_builders', 'After Builders Clean'), ('custom_one_off', 'Custom One Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotetemplate',
            name='cleaning_type',
            field=models.CharField(choices=[('general', 'General Cleaning'), ('deep', 'Deep Cleaning'), ('end_of_lease', 'End of Lease Cleaning'), ('ndis', 'NDIS Cleaning'), ('commercial', 'Commercial Cleaning'), ('carpet', 'Carpet Cleaning'), ('window', 'Window Cleaning'), ('pressure_washing', 'Pressure Washing'), ('airbnb', 'Airbnb Turnover'), ('post_renovation', 'Post Renovation'), ('after_builders', 'After Builders Clean'), ('custom_one_off', 'Custom One Off')], help_text='Default cleaning type', max_length=20),
        ),
    ]
